export default {
  status: 1,
  complete: 1,
  list: {
    '2141006632': {
      item_id: '2141006632',
      resolved_id: '2136888548',
      given_url: 'https://',
      favorite: '0',
      status: '0',
      time_added: '1',
      time_updated: '3',
      time_read: '0',
      time_favorited: '0',
      sort_id: 0,
      resolved_title: 'Title for foo',
      resolved_url: 'https://',
      excerpt: 'Foo',
      is_article: '1',
      is_index: '0',
      has_video: '0',
      has_image: '0',
      word_count: '2021',
      lang: 'en',
      time_to_read: 9,
      domain_metadata: {
        name: 'Bar',
        logo: 'https://',
        greyscale_logo: 'https://',
      },
      listen_duration_estimate: 782,
    },
    '2141007284': {
      item_id: '2141007284',
      resolved_id: '2138556663',
      given_url: 'https://',
      given_title: 'Bar',
      favorite: '0',
      status: '0',
      time_added: '2',
      time_updated: '4',
      time_read: '4',
      time_favorited: '0',
      sort_id: 1,
      resolved_title: 'Bar',
      resolved_url: 'https://',
      excerpt: 'Excerpt for Bar',
      is_article: '1',
      is_index: '0',
      has_video: '0',
      has_image: '1',
      word_count: '1002',
      lang: 'en',
      time_to_read: 5,
      top_image_url: 'http://',
      domain_metadata: {
        name: 'Bar Author',
        logo: 'https://',
        greyscale_logo: 'https://',
      },
      listen_duration_estimate: 388,
    },
  },
};
